# Generated by Django 3.0 on 2019-12-16 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Language',
        ),
    ]
