# Generated by Django 3.0 on 2019-12-16 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_delete_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name']},
        ),
    ]
